[project]
name = "technova"
version = "0.1.0"
description = "Projet TechNova pour analyser les causes de dÃ©mission"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.14.7",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "uv>=0.9.15",
]
